version 2:

models:
  - name: fact_indemnizatii
    columns:
      - name: pk
        tests:
          - not_null
          - unique
        
  - name: dim_persoane
    columns:
      - name: person_id
        tests:
          - not_null
          - unique

  - name: dim_companii
    columns:
      - name: company_id
        tests:
          - not_null
          - unique