version 2:

models:
  - name: fact_indemnizatii
    columns:
      - name: pk
        tests:
          - not_null
          - unique

      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_persoane')
              field: person_id
      
      - name: company_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_companii')
              field: company_id
        
      - name: an_raportare
        tests:
          - not_null
        
  - name: dim_persoane
    columns:
      - name: person_id
        tests:
          - not_null
          - unique

  - name: dim_companii
    columns:
      - name: company_id
        tests:
          - not_null
          - unique